'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={data:[],scored:[],preferences:new Set(['nature','mountains','gastronomy','history']),budgetMode:'person',transport:'both',travellers:2,nights:4,days:5,budget:15000,tourism:'less',weather:'20-25',month:8,visible:12,compare:new Set(),map:null,markers:[]};
const PREFS={nature:'Příroda',mountains:'Hory',sea:'Moře',lakes:'Jezera',beaches:'Pláže',hiking:'Hiking',cycling:'Cyklistika',running:'Běh',waterActivities:'Vodní aktivity',history:'Historie',architecture:'Architektura',culture:'Kultura',gastronomy:'Gastronomie',nightlife:'Noční život',cafes:'Kavárny',localAtmosphere:'Lokální atmosféra',authenticity:'Autenticita',activeHoliday:'Outdoor',cityNatureCombo:'Město + příroda'};
const CZK=25;
function clamp(v,a=0,b=100){return Math.max(a,Math.min(b,v))}
function mean(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:60}
function midpoint(r){return (r.min+r.max)/2}
function dates(){const a=new Date(dateFrom.value),b=new Date(dateTo.value);if(!isNaN(a)&&!isNaN(b)&&b>a){state.nights=Math.round((b-a)/86400000);state.days=state.nights+1;state.month=a.getMonth()+1}durationLabel.textContent=`${state.days} dní / ${state.nights} nocí`}
function estimate(d){const lodging=midpoint(d.costs.accommodationPerNight)*state.nights;const food=midpoint(d.costs.foodPerDay)*state.days*state.travellers;const local=midpoint(d.costs.localTransportPerDay)*state.days*state.travellers;const activities=midpoint(d.costs.activitiesPerDay)*state.days*state.travellers;let transport=0;if(state.transport==='car'||(state.transport==='both'&&d.transport.carFromOlomouc.suitable)){transport=(d.transport.carFromOlomouc.distanceKm||800)*2*.16*1.65+35}else transport=midpoint(d.transport.flight.roundTripCzk)/CZK*state.travellers;const totalEur=lodging+food+local+activities+transport;return {lodging:lodging*CZK,food:food*CZK,local:local*CZK,activities:activities*CZK,transport:transport*CZK,total:totalEur*CZK,perPerson:totalEur*CZK/state.travellers}}
function preferenceScore(d){return mean([...state.preferences].map(k=>(d.scores[k]??5)*10))}
function weatherScore(d){const m=d.seasonality[String(state.month)],targets={cool:[8,18],'15-20':[15,20],'20-25':[20,25],'25-30':[25,30],hot:[25,38],pleasant:[15,27]},[lo,hi]=targets[state.weather];const t=m.dayTempC,delta=t<lo?lo-t:t>hi?t-hi:0;return clamp(m.suitability*10-delta*5-(t>32&&state.weather!=='hot'?18:0))}
function priceScore(d,cost){const limit=state.budgetMode==='person'?state.budget:state.budget/state.travellers,ratio=cost.perPerson/limit;return ratio<=.8?100:ratio<=1?85:clamp(85-(ratio-1)*90,10,85)}
function accessScore(d){const car=d.transport.carFromOlomouc,flight=d.transport.flight;let ok=state.transport==='car'?car.suitable:state.transport==='flight'?flight.availability!=='bez přímého spojení':car.suitable||flight.availability!=='bez přímého spojení';if(!ok)return 10;let base=d.scores.accessibility*10;if(state.transport==='car'&&car.hours)base-=Math.max(0,car.hours-6)*4;return clamp(base)}
function tourismScore(d){const m=d.seasonality[String(state.month)],t=Math.max(d.tourismLevel,m.tourism);if(state.tourism==='any')return 70;if(state.tourism==='less')return clamp(110-t*10);if(state.tourism==='low')return clamp(120-t*13);return clamp((d.authenticity*7)+(10-t)*3)}
function durationScore(d){return (state.days<=2?d.staySuitability.weekend:state.days<=4?d.staySuitability['3to4Days']:state.days<=7?d.staySuitability['5to7Days']:d.staySuitability.longer)*10}
function scoreDestination(d){const cost=estimate(d),components={preference:preferenceScore(d),weather:weatherScore(d),price:priceScore(d,cost),access:accessScore(d),activities:mean([d.scores.activeHoliday*10,d.scores.cityNatureCombo*10,d.scores.nature*10,durationScore(d)]),authenticity:mean([d.authenticity*10,d.hiddenGemScore*10,d.hipsterScore*10]),tourism:tourismScore(d)};const score=Math.round(components.preference*.30+components.weather*.15+components.price*.15+components.access*.10+components.activities*.15+components.authenticity*.10+components.tourism*.05);const good=[],bad=[];if(components.preference>75)good.push('silná shoda s vybranými zájmy');if(components.weather>75)good.push('dobré klimatické podmínky v daném měsíci');if(components.price>80)good.push('vejde se do zadaného rozpočtu');if(components.access>75)good.push('praktická dostupnost z Olomouce');if(d.hiddenGemScore>=7)good.push('nadprůměrný Hidden Gem Score');if(components.price<65)bad.push('orientačně nad rozpočtem');if(components.weather<55)bad.push('termín není klimaticky ideální');if(components.tourism<55)bad.push('vyšší turistická zátěž');if(components.access<50)bad.push('složitější doprava');return {...d,score,components,cost,good:good.slice(0,5),bad:bad.slice(0,4),month:d.seasonality[String(state.month)]}}
function recompute(){dates();state.budget=+budget.value;state.travellers=+travellers.value;state.tourism=tourismPref.value;state.weather=weatherPref.value;state.scored=state.data.map(scoreDestination);render()}
function filtered(){let a=[...state.scored],q=textFilter.value.trim().toLowerCase(),c=countryFilter.value;if(q)a=a.filter(d=>(d.name+' '+d.country+' '+d.region).toLowerCase().includes(q));if(c)a=a.filter(d=>d.country===c);const k=sort.value;a.sort((x,y)=>k==='price'?x.cost.perPerson-y.cost.perPerson:k==='weather'?y.components.weather-x.components.weather:k==='authenticity'?y.authenticity-x.authenticity:k==='tourism'?x.tourismLevel-y.tourismLevel:k==='nature'?y.scores.nature-x.scores.nature:k==='gastronomy'?y.scores.gastronomy-x.scores.gastronomy:k==='access'?y.components.access-x.components.access:y.score-x.score);return a}
function card(d,i){const over=d.components.price<65;return `<article class="card"><div class="card-image" style="background-image:url('${d.image}')"><span class="rank">#${i+1}</span><span class="score">${d.score}/100</span></div><div class="card-content"><h3>${d.name}</h3><div class="meta">${d.country} · ${d.region}</div><p class="reason">${d.good[0]||d.summary}. ${d.good[1]||''}</p><div class="metrics"><div class="metric">Cena / osoba<b class="${over?'over':''}">${Math.round(d.cost.perPerson).toLocaleString('cs-CZ')} Kč ${over?'· nad rozpočtem':''}</b></div><div class="metric">Doprava<b>${d.transport.recommended}</b></div><div class="metric">Počasí<b>${d.month.dayTempC} °C · déšť ${d.month.raininess}/10</b></div><div class="metric">Turismus / autenticita<b>${d.tourismLevel}/10 · ${d.authenticity}/10</b></div></div><div class="chips">${d.activities.slice(0,4).map(x=>`<span class="chip">${x}</span>`).join('')}</div><div class="card-actions"><button onclick="toggleCompare('${d.id}')">＋ Porovnat</button><button class="detail" onclick="openDetail('${d.id}')">Detail destinace</button></div></div></article>`}
function render(){const a=filtered();cards.innerHTML=a.slice(0,state.visible).map(card).join('');resultSummary.textContent=`${a.length} výsledků · ${state.days} dní · ${state.month}. měsíc · rozpočet ${state.budget.toLocaleString('cs-CZ')} Kč ${state.budgetMode==='person'?'na osobu':'celkem'}`;loadMore.style.display=state.visible<a.length?'block':'none';renderMap(a.slice(0,50))}
function bars(d){return ['nature','mountains','sea','lakes','hiking','cycling','history','gastronomy','cafes','authenticity'].map(k=>`<div class="bar">${PREFS[k]||k} ${d.scores[k]}/10<i style="--v:${d.scores[k]*10}%"></i></div>`).join('')}
window.openDetail=id=>{const d=state.scored.find(x=>x.id===id);modalBody.innerHTML=`<header class="detail-hero" style="background-image:url('${d.image}')"><button class="close" onclick="closeModal()">×</button><span class="kicker">${d.character}</span><h2>${d.name}</h2><p>${d.country} · ${d.region} · ${d.score}/100</p></header><div class="detail-body"><div class="detail-grid"><main><section class="box"><h3>Proč právě sem</h3><p>${d.summary}</p><ul>${d.good.map(x=>`<li>${x}</li>`).join('')}</ul></section><section class="proscons"><div class="pros"><b>Proč jet</b><ul>${d.pros.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="cons"><b>Co může být problém</b><ul>${[...d.cons,...d.bad].slice(0,6).map(x=>`<li>${x}</li>`).join('')}</ul></div></section><section class="box"><h3>Co lze dělat během 4 dnů</h3>${d.itinerary4Days.map((x,i)=>`<div class="itinerary"><b>Den ${i+1}</b><br>${x}</div>`).join('')}</section><section class="box"><h3>Příroda, kultura a program</h3><p>Aktivity: ${d.activities.join(', ')}.</p><p>Jednodenní výlety: ${d.dayTrips.join('; ')}.</p></section><section class="box"><h3>Počasí a nejlepší období</h3><p>Pro zvolený měsíc: den ${d.month.dayTempC} °C, noc ${d.month.nightTempC} °C, deštivost ${d.month.raininess}/10, vhodnost ${d.month.suitability}/10.</p></section></main><aside><section class="box"><h3>Skóre</h3><div class="bars">${bars(d)}</div></section><section class="box"><h3>Orientační rozpočet</h3><p>Celkem: <b>${Math.round(d.cost.total).toLocaleString('cs-CZ')} Kč</b></p><p>Na osobu: <b>${Math.round(d.cost.perPerson).toLocaleString('cs-CZ')} Kč</b></p><p>Ubytování ${d.costs.accommodationPerNight.min}–${d.costs.accommodationPerNight.max} € / noc</p><p>Jídlo ${d.costs.foodPerDay.min}–${d.costs.foodPerDay.max} € / den</p></section><section class="box"><h3>Doprava</h3><p><b>${d.transport.recommended}</b></p><p>Let: ${d.transport.flight.availability}; ${d.transport.flight.departureAirports.join(', ')}.</p><p>Auto: ${d.transport.carFromOlomouc.suitable?`${d.transport.carFromOlomouc.hours} h / cca ${d.transport.carFromOlomouc.distanceKm} km`:'spíše nevhodné'}</p></section><section class="box"><small>${d.dataQuality}</small></section></aside></div></div>`;modal.classList.add('show');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'};
window.closeModal=()=>{modal.classList.remove('show');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''};modal.onclick=e=>{if(e.target===modal)closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
window.toggleCompare=id=>{state.compare.has(id)?state.compare.delete(id):state.compare.size<4&&state.compare.add(id);compareBar.classList.toggle('show',state.compare.size>0);compareCount.textContent=`${state.compare.size} vybraných`};compareClear.onclick=()=>{state.compare.clear();compareBar.classList.remove('show')};compareBtn.onclick=()=>{const ds=[...state.compare].map(id=>state.scored.find(x=>x.id===id));modalBody.innerHTML=`<div class="detail-body"><button class="close" onclick="closeModal()">×</button><h2>Porovnání destinací</h2><div style="overflow:auto"><table class="compare-table"><tr><th>Destinace</th>${ds.map(d=>`<th>${d.name}</th>`).join('')}</tr>${[['Skóre',d=>d.score+'/100'],['Cena/os.',d=>Math.round(d.cost.perPerson).toLocaleString('cs-CZ')+' Kč'],['Doprava',d=>d.transport.recommended],['Počasí',d=>d.month.dayTempC+' °C'],['Příroda',d=>d.scores.nature+'/10'],['Hory',d=>d.scores.mountains+'/10'],['Moře',d=>d.scores.sea+'/10'],['Historie',d=>d.scores.history+'/10'],['Gastronomie',d=>d.scores.gastronomy+'/10'],['Turismus',d=>d.tourismLevel+'/10'],['Autenticita',d=>d.authenticity+'/10']].map(r=>`<tr><td><b>${r[0]}</b></td>${ds.map(d=>`<td>${r[1](d)}</td>`).join('')}</tr>`).join('')}</table></div></div>`;modal.classList.add('show');document.body.style.overflow='hidden'};
function renderMap(items){if(!window.L)return;if(!state.map){$('#map').innerHTML='';state.map=L.map('map').setView([48.8,13.5],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors',maxZoom:18}).addTo(state.map)}state.markers.forEach(m=>m.remove());state.markers=items.map(d=>L.marker([d.coordinates.lat,d.coordinates.lon]).addTo(state.map).bindPopup(`<b>${d.name}</b><br>${d.score}/100<br><button onclick="openDetail('${d.id}')">Detail</button>`))}
function initInputs(){const now=new Date(),start=new Date(now.getFullYear(),7,13),end=new Date(now.getFullYear(),7,18);dateFrom.value=start.toISOString().slice(0,10);dateTo.value=end.toISOString().slice(0,10);preferenceChips.innerHTML=Object.entries(PREFS).map(([k,v])=>`<button type="button" class="chip ${state.preferences.has(k)?'on':''}" data-pref="${k}">${v}</button>`).join('');preferenceChips.onclick=e=>{const b=e.target.closest('[data-pref]');if(!b)return;state.preferences.has(b.dataset.pref)?state.preferences.delete(b.dataset.pref):state.preferences.add(b.dataset.pref);b.classList.toggle('on');recompute()};$$('[data-budget-mode]').forEach(b=>b.onclick=()=>{$$('[data-budget-mode]').forEach(x=>x.classList.remove('on'));b.classList.add('on');state.budgetMode=b.dataset.budgetMode;recompute()});$$('[data-transport]').forEach(b=>b.onclick=()=>{$$('[data-transport]').forEach(x=>x.classList.remove('on'));b.classList.add('on');state.transport=b.dataset.transport;recompute()});[dateFrom,dateTo,budget,travellers,tourismPref,weatherPref].forEach(x=>x.onchange=recompute);plannerForm.onsubmit=e=>{e.preventDefault();recompute();results.scrollIntoView({behavior:'smooth'})};textFilter.oninput=render;countryFilter.onchange=render;sort.onchange=render;loadMore.onclick=()=>{state.visible+=12;render()};mobilePlannerBtn.onclick=()=>planner.scrollIntoView({behavior:'smooth'})}
(async()=>{try{state.data=await fetch('destinations.json').then(r=>{if(!r.ok)throw Error(r.status);return r.json()})}catch(e){document.body.innerHTML='<main style="padding:40px"><h1>Data se nepodařilo načíst</h1><p>Spusťte projekt přes lokální HTTP server, ne dvojklikem na index.html. Viz README.md.</p></main>';return}countryFilter.innerHTML+=[...new Set(state.data.map(d=>d.country))].sort().map(c=>`<option>${c}</option>`).join('');initInputs();recompute()})();
